cluster: "test-ebpf-agent-cluster"
licenseKey: "1234567890abcdef1234567890abcdef12345678"
protocols:
  http: true
  kafka: true
  mysql: true
  redis: true
  mongodb: true
  amqp: true
  cass: true
  dns: true
  pgsql: true
